server {
    # enable for Authelia
    include /config/nginx/snippets/authelia-location.conf;

    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name {{ headscale_ui.subdomain }}.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/snippets/authelia-authrequest.conf;

        allow {{ local_ip_range }};
        allow {{ docker_ip_range }};
        allow {{ tailscale_ip_range }};
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app {{ headscale_ui.forward_host }};
        set $upstream_port {{ headscale_ui.forward_port }};
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Accept-Encoding "";
        sub_filter "</head>" "<script src=\"/web/init.js\"></script></head>";
        sub_filter_once on;
    }
}
