server {
    # enable for Authelia
    include /config/nginx/snippets/authelia-location.conf;

    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name {{ headplane.subdomain }}.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location = /headplane-init.js {
        alias /config/nginx/headplane-init.js;
        add_header Content-Type application/javascript;
    }

    location = / {
        return 302 /admin/;
    }

    location / {
        include /config/nginx/snippets/authelia-authrequest.conf;

        allow {{ local_ip_range }};
        allow {{ tailscale_ip_range }};
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app {{ headplane.forward_host }};
        set $upstream_port {{ headplane.forward_port }};
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_buffering off;
        sub_filter "</head>" "<script src=\"/headplane-init.js\"></script></head>";
        sub_filter_once on;
    }
}
