---
# ansible-playbook remove_service.yml -e subdomain=octoprint
- name: Remove subdomain from reverse proxy
  hosts: server
  become: true

  vars_files:
    - secret.yml

  pre_tasks:
    - name: Verify required variables
      assert:
        that:
          - subdomain is defined
        fail_msg: "Missing required variable. Need: subdomain"

    - name: Get User and Group IDs
      getent:
        database: passwd
      tags:
        - always

    - name: Set User and Group IDs as facts
      set_fact:
        uid: "{{ ansible_facts['getent_passwd'][user][1] }}"
        gid: "{{ ansible_facts['getent_passwd'][user][2] }}"
        user_home: "{{ ansible_facts['getent_passwd'][user][4] }}"
      tags:
        - always

  tasks:
    - name: Check if configuration file exists
      stat:
        path: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ subdomain }}.subdomain.conf"
      register: config_file

    - name: "Remove {{ subdomain }} service"
      when: config_file.stat.exists
      block:
        - name: Backup existing configuration
          copy:
            src: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ subdomain }}.subdomain.conf"
            dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ subdomain }}.subdomain.conf.bak"
            remote_src: yes

        - name: Remove proxy configuration file
          file:
            path: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ subdomain }}.subdomain.conf"
            state: absent

        - name: Restart swag
          include_tasks: tasks/restart_swag.yml

        - debug: msg="{{ subdomain }} subdomain removed from reverse proxy"

    - debug: msg="'{{ subdomain }}' config not found, nothing to do."
      when: not config_file.stat.exists
