---
- name: Setup vpn
  hosts: server
  become: true
  vars:
    is_raspberry_pi: "{{ 'raspberry pi' in (ansible_facts['product_name'] | default('') | lower) }}"

  vars_files:
    - secret.yml

  pre_tasks:
    - name: Get User and Group IDs
      getent:
        database: passwd
      tags:
        - always

    - name: Set User and Group IDs as facts
      set_fact:
        uid: "{{ ansible_facts['getent_passwd'][user][1] }}"
        gid: "{{ ansible_facts['getent_passwd'][user][2] }}"
        user_home: "{{ ansible_facts['getent_passwd'][user][4] }}"
      tags:
        - always

  roles:
    - role: docker
      tags:
        - docker

    - role: ufw
      tags:
        - ufw

    - role: ddclient
      tags:
        - ddclient

    - role: wireguard
      tags:
        - wireguard

    - role: portainer
      tags:
        - portainer

    - role: authelia
      tags:
        - authelia

    - role: swag
      tags:
        - swag

    - role: homer
      tags:
        - homer

    - role: adguard-unbound
      tags:
        - adguard