---
- name: Setup vpn
  hosts: server
  become: true

  vars_files:
    - secret.yml

  pre_tasks:
    - name: Get User and Group IDs
      getent:
        database: passwd
      tags:
        - always

    - name: Set User and Group IDs as facts
      set_fact:
        uid: "{{ getent_passwd[user].1 }}"
        gid: "{{ getent_passwd[user].2 }}"
        user_home: "{{ getent_passwd[user].4 }}"
      tags:
        - always

  roles:
    - role: docker
      tags:
        - docker

    - role: ufw
      tags:
        - ufw

    - role: ddclient
      tags:
        - ddclient
    
    - role: adguard-unbound
      tags:
        - adguard

    - role: authelia
      tags:
        - authelia

    - role: wireguard
      tags:
        - wireguard

    - role: watchtower
      tags:
        - watchtower

    - role: portainer
      tags:
        - portainer

    - role: swag
      tags:
        - swag

    - role: homer
      tags:
        - homer