---
- name: Setup VPS (Headscale raw-TCP relay)
  hosts: vps
  become: true
  vars_files:
    - secret.yml

  pre_tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      tags:
        - always

  roles:
    - role: vps_relay
      tags:
        - vps_relay
