---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Deploy 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
  notify: restart unattended-upgrades

- name: Deploy 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'
  notify: restart unattended-upgrades

- name: Enable and start unattended-upgrades
  service:
    name: unattended-upgrades
    enabled: yes
    state: started
