
---
- name: Create the config folder
  file:
    path: "{{ docker_dir }}/authelia"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy the main config
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/authelia/configuration.yml"
    owner: root
    group: root
    mode: "0644"

- name: Copy the users database
  template:
    src: users_database.yml.j2
    dest: "{{ docker_dir }}/authelia/users_database.yml"
    owner: root
    group: root
    mode: "0644"

- name: Make sure the Redis container is created and running
  docker_container:
    name: redis
    image: redis:alpine
    networks:
      - name: docker_network
        ipv4_address: "{{ redis.docker_address }}"
    pull: yes
    state: started
    restart_policy: unless-stopped

- name: Make sure the Authelia container is created and running
  docker_container:
    name: authelia
    image: authelia/authelia:latest
    networks:
      - name: docker_network
        ipv4_address: "{{ authelia.docker_address }}"
    pull: yes
    state: started
    restart: yes
    volumes:
      - "{{ docker_dir }}/authelia:/config"
    restart_policy: unless-stopped
  
- name: Add a 2FA alias to .bashrc
  blockinfile:
    path: "/home/{{ user }}/.bashrc"
    create: yes
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"
    state: present
    block: |
      alias show_2fa="sudo cat {{ docker_dir }}/authelia/notification.txt"
  notify:
    - Source .bashrc