---
- name: Make sure the Portainer container is created and running
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    pull: yes
    networks:
      - name: docker_network
        ipv4_address: "{{ portainer.docker_address }}"
    state: started
    restart: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - "{{ docker_dir }}/portainer:/data"
    restart_policy: unless-stopped
