---
- name: Create directory for 'adguard-unbound-build'
  file:
    path: "{{ docker_dir }}/adguard-unbound-build"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy content of directory 'adguard-unbound-build'
  copy:
    src: adguard-unbound-build/
    dest: "{{ docker_dir }}/adguard-unbound-build"

- name: Build the adguard-unbound Docker image
  docker_image:
    name: adguard-unbound
    build:
      path: "{{ docker_dir }}/adguard-unbound-build"
    source: build
  notify: Restart adguard-unbound

- name: Create the adguard-unbound config folders
  file:
    path: "{{ docker_dir }}/{{ item }}"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"
  loop:
    - adguard-unbound
    - adguard-unbound/adguard
    - adguard-unbound/adguard/work
    - adguard-unbound/adguard/conf
    - adguard-unbound/dnscrypt-proxy

- name: Copy Adguard config
  copy:
    src: AdGuardHome.yaml
    dest: "{{ docker_dir }}/adguard-unbound/adguard/conf/AdGuardHome.yaml"
  notify: Restart adguard-unbound

- name: Template the dnscrypt-proxy config
  template:
    src: dnscrypt-proxy.toml.j2
    dest: "{{ docker_dir }}/adguard-unbound/dnscrypt-proxy/dnscrypt-proxy.toml"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"
  notify: Restart adguard-unbound

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped

- name: Disable DNSStubListener
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: DNSStubListener=no
    regexp: ^#?DNSStubListener=(yes|no)$

- name: Make sure the adguard-unbound container is created and running
  docker_container:
    name: adguard-unbound
    image: adguard-unbound
    networks:
      - name: docker_network
        ipv4_address: "{{ adguard.docker_address }}"
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/adguard-unbound/dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
      - "{{ docker_dir }}/adguard-unbound/adguard/work:/opt/adguardhome/work"
      - "{{ docker_dir }}/adguard-unbound/adguard/conf:/opt/adguardhome/conf"
    ports:
      - "{{ dns_port }}:53/udp"
      - "{{ dns_port }}:53/tcp"
      - "{{ bootp_server_port }}:67/udp"

- name: Start systemd-resolved
  systemd:
    name: systemd-resolved
    state: started