---
- name: Add user "{{ user }}" to docker group 
  user:
    name: '{{ user }}'
    groups:
      - docker
    append: yes
    
- name: Create the wg network
  docker_network:
    name: wg_network
    ipam_config:
      - subnet: 10.8.2.0/24
        gateway: 10.8.2.1
        iprange: 10.8.2.0/24