---
- name: Create the docker network
  docker_network:
    name: docker_network
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"
        gateway: "{{ docker_gateway }}" 
        iprange: "{{ docker_ip_range }}"