---
- name: Create the folders
  file:
    path: "{{ docker_dir }}/bunkerweb/data"
    recurse: yes
    owner: root
    group: 101
    mode: "0770"

- name: Copy the env file
  template:
    src: env.j2
    owner: root
    group: 101
    mode: "0644"
    dest: "{{ docker_dir }}/bunkerweb/.env"

- name: Make sure the Bunkerweb container is created and running
  docker_container:
    name: bunkerweb
    image: bunkerity/bunkerweb:1.4.8
    networks:
      - name: docker_network
        ipv4_address: "{{ bunkerweb_network_address }}"
    pull: yes
    restart: yes
    state: started
    env_file: "{{ docker_dir }}/bunkerweb/.env"
    ports:
      - "{{ http_port }}:8080"
      - "{{ https_port }}:8443"
    volumes:
      - "{{ docker_dir }}/bunkerweb/data:/data"
      - /lib/modules:/lib/modules
    restart_policy: unless-stopped