---
- name: Make sure the Wireguard container is created and running
  docker_container:
    name: wireguard
    image: weejewel/wg-easy:7
    pull: yes
    networks:
      - name: docker_network
        ipv4_address: "{{ wireguard_docker_network }}"
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    state: started
    env:
      WG_HOST: "{{ wireguard_subdomain }}"
      WG_PORT: "{{ wireguard_port }}"
      WG_DEFAULT_DNS: "{{ adguard_network_address }}"
    ports:
      - "{{ wireguard_port }}:51820/udp"
    volumes:
      - "{{ docker_dir }}/wireguard:/etc/wireguard"
    restart_policy: unless-stopped
  notify: Restart wireguard